[package]
name = "eden-agent-connector-hoi4"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
eden-agent-connector-protocol = { path = "../../../../Server/crates/eden-agent-connector-protocol" }
eden-agent-hoi4 = { path = "../../../../Server/crates/eden-agent-hoi4" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true

[dev-dependencies]
eden-agent-connector-host = { path = "../../../../Server/crates/eden-agent-connector-host" }
eden-agent-connector-package = { path = "../../../../Server/crates/eden-agent-connector-package" }
eden-agent-connectors = { path = "../../../../Server/crates/eden-agent-connectors" }
eden-agent-store = { path = "../../../../Server/crates/eden-agent-store" }
tempfile.workspace = true
