import { readFile, readdir, mkdir, writeFile, rename, rm } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { createHash, randomUUID } from 'node:crypto'
import path from 'node:path'

// Generation only reads TS contracts and the browser template; no host, Data or Cargo imports.
if (process.argv.length !== 2) throw new Error('Usage: npm run generate:rpc')
const root = fileURLToPath(new URL('../../', import.meta.url))
const template = await readFile(new URL('./templates/rpc-browser.ts.template', import.meta.url), 'utf8')
const hash = createHash('sha256')
await hashContracts(path.join(root, 'packages/api/src'))
const clientRuntime = await readFile(path.join(root, 'frontend/web/src/lib/rpc-client.ts'), 'utf8')
const blobRuntime = await readFile(path.join(root, 'frontend/web/src/lib/blob-upload.ts'), 'utf8')
const digest = hash.update(template).update('\0rpc-client\0').update(clientRuntime).update('\0blob-upload\0').update(blobRuntime).digest('hex')
const output = path.join(root, 'frontend/web/src/generated/eden-agent-rpc.ts')
const content = `/* eslint-disable */\n// @generated by npm run generate:rpc. Do not edit by hand.\n// Source digest: ${digest}\n\n${template}`
await mkdir(path.dirname(output), { recursive: true })
const temporary = `${output}.staging-${randomUUID()}`
try {
  await writeFile(temporary, content, { flag: 'wx' })
  await rename(temporary, output)
} finally { await rm(temporary, { force: true }) }
process.stdout.write('Generated Eden RPC browser client from TypeScript contracts and template\n')

async function hashContracts(directory, prefix = '') {
  const entries = await readdir(directory, { withFileTypes: true })
  entries.sort((a, b) => a.name < b.name ? -1 : a.name > b.name ? 1 : 0)
  for (const entry of entries) {
    const relative = `${prefix}${entry.name}`, target = path.join(directory, entry.name)
    if (entry.isDirectory()) await hashContracts(target, `${relative}/`)
    else if (entry.isFile() && entry.name.endsWith('.ts')) hash.update(relative).update('\0').update(await readFile(target)).update('\0')
    else if (entry.isSymbolicLink()) throw new Error('API source tree cannot contain symbolic links during generation')
  }
}
