import { useState, useRef, useEffect } from 'react';
import { Send, Paperclip, ImageIcon, Mic, StopCircle } from 'lucide-react';
import { cn } from '../lib/utils';
import { motion, AnimatePresence } from 'motion/react';

interface ChatInputProps {
  onSend: (text: string, images: string[]) => void;
  disabled?: boolean;
}

export function ChatInput({ onSend, disabled }: ChatInputProps) {
  const [input, setInput] = useState('');
  const [images, setImages] = useState<string[]>([]);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  // Auto-resize textarea
  useEffect(() => {
    if (textareaRef.current) {
      textareaRef.current.style.height = 'auto';
      const newHeight = Math.min(textareaRef.current.scrollHeight, 200);
      textareaRef.current.style.height = `${newHeight}px`;
    }
  }, [input]);

  const handleSend = () => {
    if ((!input.trim() && images.length === 0) || disabled) return;
    onSend(input.trim(), images);
    setInput('');
    setImages([]);
    if (textareaRef.current) {
      textareaRef.current.style.height = 'auto'; // Reset size
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  const handlePaste = (e: React.ClipboardEvent) => {
    const items = e.clipboardData.items;
    for (const item of items) {
      if (item.type.indexOf('image') === 0) {
        const file = item.getAsFile();
        if (file) {
          const reader = new FileReader();
          reader.onload = (e) => {
            if (e.target?.result && typeof e.target.result === 'string') {
              setImages(prev => [...prev, e.target!.result as string]);
            }
          };
          reader.readAsDataURL(file);
        }
      }
    }
  };

  const removeImage = (index: number) => {
    setImages(prev => prev.filter((_, i) => i !== index));
  };

  return (
    <div className="relative -mx-4 md:mx-0 px-4 md:px-0 bg-bg/90 backdrop-blur-md pt-4 pb-6 md:pb-8 border-t border-border z-10 sticky bottom-0">
      
      {/* Image Previews */}
      <AnimatePresence>
        {images.length > 0 && (
          <motion.div 
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: 10 }}
            className="flex gap-2 mb-3 max-w-3xl mx-auto px-2 overflow-x-auto"
          >
            {images.map((img, idx) => (
              <div key={idx} className="relative group flex-shrink-0">
                 <img src={img} alt="preview" className="h-16 w-16 object-cover rounded-xl border border-border shadow-sm" />
                 <button 
                  onClick={() => removeImage(idx)}
                  className="absolute -top-2 -right-2 bg-card text-accent border border-border rounded-full p-0.5 opacity-0 group-hover:opacity-100 transition-opacity"
                 >
                    <StopCircle className="w-4 h-4" />
                 </button>
              </div>
            ))}
          </motion.div>
        )}
      </AnimatePresence>

      {/* Input Box */}
      <div className="max-w-3xl mx-auto pt-2 pl-4 pr-2 pb-2 bg-card border border-border rounded-full shadow-lg flex items-end gap-2 focus-within:border-accent/50 transition-all">
        
        <button className="flex-shrink-0 pb-2 text-text-muted hover:text-text transition-colors">
          <Paperclip className="w-5 h-5" />
        </button>

        <textarea
          ref={textareaRef}
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={handleKeyDown}
          onPaste={handlePaste}
          placeholder="Send a message... (Shift+Enter for new line)"
          rows={1}
          className="w-full max-h-[200px] resize-none bg-transparent outline-none pb-2 pt-2 text-text placeholder:text-text-muted text-[15px] leading-relaxed font-sans"
        />

        {input.trim() || images.length > 0 ? (
          <motion.button 
            initial={{ scale: 0.8, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            onClick={handleSend}
            disabled={disabled}
            className="flex-shrink-0 p-2.5 mb-1 border border-accent-dim text-accent rounded-full hover:bg-accent/10 hover:border-accent transition duration-200 active:scale-95 disabled:opacity-50"
          >
            <Send className="w-4 h-4 ml-0.5" />
          </motion.button>
        ) : (
           <button className="flex-shrink-0 p-2.5 mb-1 text-text-muted hover:text-text transition-colors">
            <Mic className="w-5 h-5" />
          </button>
        )}
      </div>
      
      <div className="text-center mt-3 text-xs text-text-muted uppercase tracking-[0.1em]">
        Content generated by AI may be inaccurate.
      </div>
    </div>
  );
}
