[package]
name = "eden-agent-connector-lichess"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
futures.workspace = true
eden-agent-connector-protocol = { path = "../../../../Server/crates/eden-agent-connector-protocol" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
shakmaty.workspace = true
tokio.workspace = true
tokio-util.workspace = true

[dev-dependencies]
eden-agent-connector-host = { path = "../../../../Server/crates/eden-agent-connector-host" }
eden-agent-connector-package = { path = "../../../../Server/crates/eden-agent-connector-package" }
tempfile.workspace = true
